export const ADD_PUBLICATION = 'ADD_PUBLICATION'
export const CHANGE_PUBLICATION_INPUT = 'CHANGE_PUBLICATION_INPUT'
<<<<<<< HEAD
export const SET_USERS = 'SET_USERS'
export const TOGGLE_FOLLOWING = 'TOGGLE_FOLLOWING'
export const GET_TOTAL_USERS_COUNT = 'GET_TOTAL_USERS_COUNT'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE'
export const AUTHENTICATION = 'SET_AUTHENTICATION_STATUS'
export const SET_RESPONSE_WAITING = 'SET_RESPONSE_WAITING'
export const SET_PROFILE_LOADING_STATUS = 'SET_LOADING_STATUS'
export const SET_FOLLOW_BUTTON_LOADING_STATUS = 'SET_FOLLOW_BUTTON_LOADING_STATUS'
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER'
export const SET_FOLLOWING_STATUS = 'SET_FOLLOWING_STATUS'
=======
export const GET_USERS = "GET_USERS"
export const TOGGLE_FOLLOW = "TOGGLE_FOLLOW"
>>>>>>> c6dc7ded801555ec9de26ef0600dc43e2b7d936d
