export const ADD_PUBLICATION = "ADD_PUBLICATION"
export const CHANGE_PUBLICATION_INPUT = 'CHANGE_PUBLICATION_INPUT'
export const GET_USERS = "GET_USERS"
export const TOGGLE_FOLLOWING = "TOGGLE_FOLLOWING"
export const GET_TOTAL_USERS_COUNT = 'GET_TOTAL_USERS_COUNT'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'